//! Stage-by-stage SDXL pipeline comparison against PyTorch reference.
//!
//! Loads reference .npy tensors generated by `tests/fixtures/generate_sdxl_fixtures.py`,
//! runs the same pipeline stages in hearth, and compares outputs to find divergence.
//!
//! Usage:
//!   # First, generate reference fixtures:
//!   python tests/fixtures/generate_sdxl_fixtures.py \
//!       --model-path models/checkpoints/sd_xl_base_1.0.safetensors
//!
//!   # Then run comparison:
//!   cargo run --release --example compare_sdxl

use burn::tensor::Tensor;
use hearth::{
    clip::{ClipTokenizer, OpenClipTextEncoder, SdxlClipLTextEncoder, SdxlConditioning},
    model_loader::{self, SafeTensorsFile},
    types::Backend,
    unet::{DenoisingUnet, SdxlUnet2D, UnetConditioning},
};
use std::{path::Path, process, time::Instant};

/// Path to the SDXL checkpoint.
const CHECKPOINT_PATH: &str = "models/checkpoints/sd_xl_base_1.0.safetensors";
/// Path to tokenizer vocabulary.
const VOCAB_PATH: &str = "models/clip/vocab.json";
/// Path to tokenizer merges.
const MERGES_PATH: &str = "models/clip/merges.txt";
/// Directory containing reference .npy fixtures.
const FIXTURES_DIR: &str = "tests/fixtures";

/// Prompt used for fixture generation (must match Python script).
const PROMPT: &str = "a cat";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== SDXL Pipeline Stage-by-Stage Comparison ===\n");

    // Check prerequisites
    let checkpoint_path = Path::new(CHECKPOINT_PATH);
    if !checkpoint_path.exists() {
        eprintln!("Checkpoint not found: {CHECKPOINT_PATH}");
        process::exit(1);
    }

    let fixtures_dir = Path::new(FIXTURES_DIR);
    let token_fixture = fixtures_dir.join("sdxl_tokens.npy");
    if !token_fixture.exists() {
        eprintln!("Fixtures not found. Generate them first:");
        eprintln!(
            "  python tests/fixtures/generate_sdxl_fixtures.py --model-path {CHECKPOINT_PATH}"
        );
        process::exit(1);
    }

    let device = Default::default();
    let mut all_pass = true;

    // -------------------------------------------------------------------------
    // Stage 1: Token comparison
    // -------------------------------------------------------------------------
    println!("--- Stage 1: Tokenization ---");

    let tokenizer = ClipTokenizer::from_files(Path::new(VOCAB_PATH), Path::new(MERGES_PATH))?;

    // CLIP-L tokens (padded with EOS)
    let tokens_l = tokenizer.encode(PROMPT, &device)?;
    let tokens_l_data: Vec<i32> = tokens_l.clone().into_data().convert::<i32>().to_vec()?;

    // OpenCLIP-G tokens (padded with 0)
    let tokens_g = tokenizer.encode_open_clip(PROMPT, &device)?;
    let tokens_g_data: Vec<i32> = tokens_g.clone().into_data().convert::<i32>().to_vec()?;

    let (ref_shape, ref_tokens_l) = load_npy_i32(&token_fixture)?;
    println!(
        "  Hearth CLIP-L tokens (first 10): {:?}",
        &tokens_l_data[..10.min(tokens_l_data.len())]
    );
    println!(
        "  PyTorch CLIP-L tokens (first 10): {:?}",
        &ref_tokens_l[..10.min(ref_tokens_l.len())]
    );
    println!("  Ref shape: {ref_shape:?}");

    let tokens_l_match = tokens_l_data
        .iter()
        .zip(ref_tokens_l.iter())
        .all(|(a, b)| *a == *b);

    if tokens_l_match {
        println!("  PASS: CLIP-L tokens match exactly");
    } else {
        println!("  FAIL: CLIP-L tokens differ!");
        let diffs: Vec<_> = tokens_l_data
            .iter()
            .zip(ref_tokens_l.iter())
            .enumerate()
            .filter(|(_, (a, b))| a != b)
            .take(5)
            .collect();
        for (i, (a, b)) in &diffs {
            println!("    Position {i}: hearth={a}, pytorch={b}");
        }
        all_pass = false;
    }

    // Check OpenCLIP-G tokens if fixture exists
    let tokens_g_fixture = fixtures_dir.join("sdxl_tokens_g.npy");
    if tokens_g_fixture.exists() {
        let (_, ref_tokens_g) = load_npy_i32(&tokens_g_fixture)?;
        println!(
            "  Hearth CLIP-G tokens (first 10): {:?}",
            &tokens_g_data[..10.min(tokens_g_data.len())]
        );
        println!(
            "  PyTorch CLIP-G tokens (first 10): {:?}",
            &ref_tokens_g[..10.min(ref_tokens_g.len())]
        );
        let tokens_g_match = tokens_g_data
            .iter()
            .zip(ref_tokens_g.iter())
            .all(|(a, b)| *a == *b);
        if tokens_g_match {
            println!("  PASS: CLIP-G tokens match exactly");
        } else {
            println!("  FAIL: CLIP-G tokens differ!");
            all_pass = false;
        }
    }
    println!();

    // -------------------------------------------------------------------------
    // Stage 2: CLIP-L hidden states
    // -------------------------------------------------------------------------
    println!("--- Stage 2: CLIP-L hidden states ---");

    let start = Instant::now();
    let file = SafeTensorsFile::open(checkpoint_path)?;
    let tensors = file.tensors()?;
    println!("  Checkpoint loaded in {:?}", start.elapsed());

    let start = Instant::now();
    let clip_l = SdxlClipLTextEncoder::load_with_prefix(
        &tensors,
        model_loader::prefix::SDXL_CLIP_L,
        &device,
    )?;
    println!("  CLIP-L loaded in {:?}", start.elapsed());

    let clip_l_hidden = clip_l.forward_hidden_layer(tokens_l, Some(10));
    let clip_l_ref = load_npy_tensor_3d(&fixtures_dir.join("sdxl_clip_l_hidden.npy"), &device)?;

    let pass = compare_tensors_3d("CLIP-L hidden", &clip_l_hidden, &clip_l_ref, 0.05);
    if !pass {
        all_pass = false;
    }
    println!();

    // -------------------------------------------------------------------------
    // Stage 3: OpenCLIP-G hidden states + pooled
    // -------------------------------------------------------------------------
    println!("--- Stage 3: OpenCLIP-G hidden states + pooled ---");

    let start = Instant::now();
    let clip_g = OpenClipTextEncoder::load(&tensors, model_loader::prefix::SDXL_CLIP_G, &device)?;
    println!("  OpenCLIP-G loaded in {:?}", start.elapsed());

    let (clip_g_hidden, clip_g_pooled) = clip_g.forward(tokens_g);

    let clip_g_hidden_ref =
        load_npy_tensor_3d(&fixtures_dir.join("sdxl_clip_g_hidden.npy"), &device)?;
    let clip_g_pooled_ref =
        load_npy_tensor_2d(&fixtures_dir.join("sdxl_clip_g_pooled.npy"), &device)?;

    let pass_h = compare_tensors_3d("CLIP-G hidden", &clip_g_hidden, &clip_g_hidden_ref, 0.05);
    let pass_p = compare_tensors_2d("CLIP-G pooled", &clip_g_pooled, &clip_g_pooled_ref, 0.05);
    if !pass_h || !pass_p {
        all_pass = false;
    }
    println!();

    // -------------------------------------------------------------------------
    // Stage 4: Conditioning vectors
    // -------------------------------------------------------------------------
    println!("--- Stage 4: Conditioning vectors ---");

    let conditioning = SdxlConditioning::new(
        clip_l_hidden,
        clip_g_hidden,
        clip_g_pooled,
        (1024.0, 1024.0),
        (0.0, 0.0),
        (1024.0, 1024.0),
        &device,
    );

    let context_ref = load_npy_tensor_3d(&fixtures_dir.join("sdxl_context.npy"), &device)?;
    let y_ref = load_npy_tensor_2d(&fixtures_dir.join("sdxl_y.npy"), &device)?;

    let pass_c = compare_tensors_3d("context", conditioning.context(), &context_ref, 0.05);
    let pass_y = compare_tensors_2d("y", conditioning.y().unwrap(), &y_ref, 0.05);
    if !pass_c || !pass_y {
        all_pass = false;
    }
    println!();

    // -------------------------------------------------------------------------
    // Stage 5: UNet forward pass
    // -------------------------------------------------------------------------
    println!("--- Stage 5: UNet forward pass ---");

    // Free CLIP memory before loading UNet
    drop(clip_l);
    drop(clip_g);

    let start = Instant::now();
    let unet = SdxlUnet2D::load(&tensors, &device)?;
    println!("  UNet loaded in {:?}", start.elapsed());

    // Fixed input matching Python script: ones * 0.5
    let unet_input: Tensor<Backend, 4> = Tensor::ones([1, 4, 16, 16], &device) * 0.5;
    let timestep: Tensor<Backend, 1> = Tensor::from_floats([500.0f32], &device);

    let start = Instant::now();
    let unet_output = DenoisingUnet::forward(&unet, unet_input, timestep, &conditioning);
    println!("  UNet forward in {:?}", start.elapsed());

    let unet_ref = load_npy_tensor_4d(&fixtures_dir.join("sdxl_unet_output.npy"), &device)?;

    let pass = compare_tensors_4d("UNet output", &unet_output, &unet_ref, 0.5);
    if !pass {
        all_pass = false;
    }
    println!();

    // -------------------------------------------------------------------------
    // Final result
    // -------------------------------------------------------------------------
    if all_pass {
        println!("=== ALL STAGES PASSED ===");
    } else {
        println!("=== SOME STAGES FAILED ===");
        process::exit(1);
    }

    Ok(())
}

// =============================================================================
// NPY loading utilities
// =============================================================================

/// Parse NPY header and return (header_end, shape, dtype_str).
fn parse_npy_header(data: &[u8]) -> Result<(usize, Vec<usize>, String), String> {
    if data.len() < 10 || &data[0..6] != b"\x93NUMPY" {
        return Err("Invalid NPY magic number".to_string());
    }

    let major = data[6];

    let (header_len, header_start) = match major {
        1 => {
            let len = u16::from_le_bytes([data[8], data[9]]) as usize;
            (len, 10)
        }
        2 | 3 => {
            let len = u32::from_le_bytes([data[8], data[9], data[10], data[11]]) as usize;
            (len, 12)
        }
        _ => return Err(format!("Unsupported NPY version {major}")),
    };

    let header_end = header_start + header_len;
    if data.len() < header_end {
        return Err("NPY file truncated in header".to_string());
    }

    let header = std::str::from_utf8(&data[header_start..header_end])
        .map_err(|_| "Invalid UTF-8 in NPY header")?;

    let shape = parse_npy_shape(header)?;

    // Extract dtype string
    let dtype = if header.contains("'<f4'") || header.contains("'float32'") {
        "f32".to_string()
    } else if header.contains("'<i4'") || header.contains("'int32'") {
        "i32".to_string()
    } else if header.contains("'<i8'") || header.contains("'int64'") {
        "i64".to_string()
    } else {
        return Err(format!("Unsupported dtype in header: {header}"));
    };

    Ok((header_end, shape, dtype))
}

/// Parse shape tuple from NPY header.
fn parse_npy_shape(header: &str) -> Result<Vec<usize>, String> {
    let shape_start = header
        .find("'shape':")
        .ok_or("Missing 'shape' in NPY header")?;
    let after_key = &header[shape_start + 8..];

    let paren_start = after_key.find('(').ok_or("Missing '(' after 'shape'")?;
    let paren_end = after_key.find(')').ok_or("Missing ')' in shape tuple")?;

    let shape_str = &after_key[paren_start + 1..paren_end];

    let mut shape = Vec::new();
    for part in shape_str.split(',') {
        let trimmed = part.trim();
        if !trimmed.is_empty() {
            let dim: usize = trimmed
                .parse()
                .map_err(|_| format!("Invalid shape dimension: {trimmed}"))?;
            shape.push(dim);
        }
    }

    Ok(shape)
}

/// Load a .npy file containing int32 data.
fn load_npy_i32(path: &Path) -> Result<(Vec<usize>, Vec<i32>), String> {
    let data =
        std::fs::read(path).map_err(|e| format!("Failed to read {}: {e}", path.display()))?;

    let (header_end, shape, dtype) = parse_npy_header(&data)?;

    let num_elements: usize = shape.iter().product();

    match dtype.as_str() {
        "i32" => {
            let expected_bytes = num_elements * 4;
            if data.len() < header_end + expected_bytes {
                return Err("NPY file truncated".to_string());
            }
            let values: Vec<i32> = data[header_end..header_end + expected_bytes]
                .chunks_exact(4)
                .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
                .collect();
            Ok((shape, values))
        }
        "i64" => {
            let expected_bytes = num_elements * 8;
            if data.len() < header_end + expected_bytes {
                return Err("NPY file truncated".to_string());
            }
            // Downcast i64 -> i32 (token IDs fit in i32)
            let values: Vec<i32> = data[header_end..header_end + expected_bytes]
                .chunks_exact(8)
                .map(|c| {
                    i64::from_le_bytes([c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7]]) as i32
                })
                .collect();
            Ok((shape, values))
        }
        _ => Err(format!("Expected int32 or int64, got {dtype}")),
    }
}

/// Load a .npy file containing float32 data.
fn load_npy_f32(path: &Path) -> Result<(Vec<usize>, Vec<f32>), String> {
    let data =
        std::fs::read(path).map_err(|e| format!("Failed to read {}: {e}", path.display()))?;

    let (header_end, shape, dtype) = parse_npy_header(&data)?;

    if dtype != "f32" {
        return Err(format!("Expected float32, got {dtype}"));
    }

    let num_elements: usize = shape.iter().product();
    let expected_bytes = num_elements * 4;

    if data.len() < header_end + expected_bytes {
        return Err("NPY file truncated".to_string());
    }

    let floats: Vec<f32> = data[header_end..header_end + expected_bytes]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();

    Ok((shape, floats))
}

/// Load .npy as a 2D burn tensor.
fn load_npy_tensor_2d(
    path: &Path,
    device: &burn::tensor::Device<Backend>,
) -> Result<Tensor<Backend, 2>, String> {
    let (shape, data) = load_npy_f32(path)?;
    if shape.len() != 2 {
        return Err(format!("Expected 2D tensor, got shape {shape:?}"));
    }
    let tensor: Tensor<Backend, 1> = Tensor::from_floats(data.as_slice(), device);
    Ok(tensor.reshape([shape[0], shape[1]]))
}

/// Load .npy as a 3D burn tensor.
fn load_npy_tensor_3d(
    path: &Path,
    device: &burn::tensor::Device<Backend>,
) -> Result<Tensor<Backend, 3>, String> {
    let (shape, data) = load_npy_f32(path)?;
    if shape.len() != 3 {
        return Err(format!("Expected 3D tensor, got shape {shape:?}"));
    }
    let tensor: Tensor<Backend, 1> = Tensor::from_floats(data.as_slice(), device);
    Ok(tensor.reshape([shape[0], shape[1], shape[2]]))
}

/// Load .npy as a 4D burn tensor.
fn load_npy_tensor_4d(
    path: &Path,
    device: &burn::tensor::Device<Backend>,
) -> Result<Tensor<Backend, 4>, String> {
    let (shape, data) = load_npy_f32(path)?;
    if shape.len() != 4 {
        return Err(format!("Expected 4D tensor, got shape {shape:?}"));
    }
    let tensor: Tensor<Backend, 1> = Tensor::from_floats(data.as_slice(), device);
    Ok(tensor.reshape([shape[0], shape[1], shape[2], shape[3]]))
}

// =============================================================================
// Comparison utilities
// =============================================================================

/// Statistics from comparing two tensors.
struct CompareStats {
    /// Maximum absolute difference.
    max_diff: f32,
    /// Mean absolute difference.
    mean_diff: f32,
    /// Number of NaN values in hearth output.
    nan_count: usize,
    /// Number of Inf values in hearth output.
    inf_count: usize,
    /// First few positions where difference exceeds threshold.
    divergent: Vec<(usize, f32, f32)>,
}

/// Compare two f32 slices and produce statistics.
fn compare_f32_slices(hearth: &[f32], reference: &[f32], threshold: f32) -> CompareStats {
    let mut max_diff: f32 = 0.0;
    let mut total_diff: f64 = 0.0;
    let mut nan_count = 0usize;
    let mut inf_count = 0usize;
    let mut divergent = Vec::new();

    for (i, (&h, &r)) in hearth.iter().zip(reference.iter()).enumerate() {
        if h.is_nan() {
            nan_count += 1;
            if divergent.len() < 5 {
                divergent.push((i, h, r));
            }
            continue;
        }
        if h.is_infinite() {
            inf_count += 1;
            if divergent.len() < 5 {
                divergent.push((i, h, r));
            }
            continue;
        }

        let diff = (h - r).abs();
        total_diff += diff as f64;
        if diff > max_diff {
            max_diff = diff;
        }
        if diff > threshold && divergent.len() < 5 {
            divergent.push((i, h, r));
        }
    }

    let mean_diff = if hearth.is_empty() {
        0.0
    } else {
        (total_diff / hearth.len() as f64) as f32
    };

    CompareStats {
        max_diff,
        mean_diff,
        nan_count,
        inf_count,
        divergent,
    }
}

/// Print comparison results and return whether it passed.
fn report_comparison(name: &str, stats: &CompareStats, threshold: f32) -> bool {
    println!("  {name}:");
    println!("    Max diff:  {:.6}", stats.max_diff);
    println!("    Mean diff: {:.6}", stats.mean_diff);

    if stats.nan_count > 0 {
        println!("    NaN count: {} (CRITICAL)", stats.nan_count);
    }
    if stats.inf_count > 0 {
        println!("    Inf count: {} (CRITICAL)", stats.inf_count);
    }

    if !stats.divergent.is_empty() {
        println!("    Divergent values (idx, hearth, pytorch):");
        for (idx, h, r) in &stats.divergent {
            println!(
                "      [{idx}] hearth={h:.6}, pytorch={r:.6}, diff={:.6}",
                (h - r).abs()
            );
        }
    }

    let pass = stats.nan_count == 0 && stats.inf_count == 0 && stats.max_diff <= threshold * 10.0;
    if pass {
        println!("    PASS (threshold: {threshold})");
    } else {
        println!("    FAIL (threshold: {threshold})");
    }
    pass
}

/// Compare 2D tensors and report.
fn compare_tensors_2d(
    name: &str,
    hearth: &Tensor<Backend, 2>,
    reference: &Tensor<Backend, 2>,
    threshold: f32,
) -> bool {
    let h_shape: [usize; 2] = hearth.shape().dims();
    let r_shape: [usize; 2] = reference.shape().dims();

    if h_shape != r_shape {
        println!("  {name}: FAIL - shape mismatch: hearth={h_shape:?}, pytorch={r_shape:?}");
        return false;
    }

    let h_data: Vec<f32> = hearth
        .clone()
        .into_data()
        .convert::<f32>()
        .to_vec()
        .unwrap();
    let r_data: Vec<f32> = reference
        .clone()
        .into_data()
        .convert::<f32>()
        .to_vec()
        .unwrap();

    let stats = compare_f32_slices(&h_data, &r_data, threshold);
    report_comparison(name, &stats, threshold)
}

/// Compare 3D tensors and report.
fn compare_tensors_3d(
    name: &str,
    hearth: &Tensor<Backend, 3>,
    reference: &Tensor<Backend, 3>,
    threshold: f32,
) -> bool {
    let h_shape: [usize; 3] = hearth.shape().dims();
    let r_shape: [usize; 3] = reference.shape().dims();

    if h_shape != r_shape {
        println!("  {name}: FAIL - shape mismatch: hearth={h_shape:?}, pytorch={r_shape:?}");
        return false;
    }

    let h_data: Vec<f32> = hearth
        .clone()
        .into_data()
        .convert::<f32>()
        .to_vec()
        .unwrap();
    let r_data: Vec<f32> = reference
        .clone()
        .into_data()
        .convert::<f32>()
        .to_vec()
        .unwrap();

    let stats = compare_f32_slices(&h_data, &r_data, threshold);
    report_comparison(name, &stats, threshold)
}

/// Compare 4D tensors and report.
fn compare_tensors_4d(
    name: &str,
    hearth: &Tensor<Backend, 4>,
    reference: &Tensor<Backend, 4>,
    threshold: f32,
) -> bool {
    let h_shape: [usize; 4] = hearth.shape().dims();
    let r_shape: [usize; 4] = reference.shape().dims();

    if h_shape != r_shape {
        println!("  {name}: FAIL - shape mismatch: hearth={h_shape:?}, pytorch={r_shape:?}");
        return false;
    }

    let h_data: Vec<f32> = hearth
        .clone()
        .into_data()
        .convert::<f32>()
        .to_vec()
        .unwrap();
    let r_data: Vec<f32> = reference
        .clone()
        .into_data()
        .convert::<f32>()
        .to_vec()
        .unwrap();

    let stats = compare_f32_slices(&h_data, &r_data, threshold);
    report_comparison(name, &stats, threshold)
}
